#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # Bonfire requires root installation (not subdirectory)
    # Change URL is not supported for federated applications (breaks ActivityPub federation)
    exclude = ["install.subdir", "change_url"]

    test_upgrade_from.61aec7817977c6e42fabe3a40dbf67987d8debd0.name = "Upgrade from 3.6"
